//
//  CourseListModels.swift
//  SwiftbookApp
//
//  Created by Alexey Efimov on 20.02.2021.
//  Copyright (c) 2021 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CellIdentifier {
    var cellIdentifier: String { get }
    var cellHeight: Float { get }
}

enum CourseList {
    // MARK: Use cases
    
    enum ShowCourses {
        struct Response: Sendable {
            let courses: [Course]
        }
        
        struct ViewModel: Sendable {
            struct CourseCellModel: CellIdentifier {
                let name: String
                let imageURL: URL?
                
                var cellIdentifier: String {
                    "CourseCell"
                }
                
                var cellHeight: Float {
                    100
                }
                
                init(course: Course) {
                    name = course.name ?? ""
                    imageURL = course.imageUrl
                }
            }
            
            let rows: [CellIdentifier]
        }
    }
}
