//
//  CourseListInteractor.swift
//  SwiftbookApp
//
//  Created by Alexey Efimov on 20.02.2021.
//  Copyright (c) 2021 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CourseListBusinessLogic {
    func doSomething(request: CourseList.Something.Request)
}

protocol CourseListDataStore {
    //var name: String { get set }
}

final class CourseListInteractor: CourseListBusinessLogic, CourseListDataStore {
    
    var presenter: CourseListPresentationLogic?
    var worker: CourseListWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: CourseList.Something.Request) {
        worker = CourseListWorker()
        worker?.doSomeWork()
        
        let response = CourseList.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
