//
//  CourseListPresenter.swift
//  SwiftbookApp
//
//  Created by Alexey Efimov on 20.02.2021.
//  Copyright (c) 2021 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CourseListPresentationLogic {
    func presentSomething(response: CourseList.ShowCourses.Response)
}

final class CourseListPresenter: CourseListPresentationLogic {
    
    weak var viewController: CourseListDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: CourseList.ShowCourses.Response) {
        let viewModel = CourseList.ShowCourses.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
