//
//  CourseListInteractor.swift
//  SwiftbookApp
//
//  Created by Alexey Efimov on 20.02.2021.
//  Copyright (c) 2021 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CourseListBusinessLogic {
    func fetchCourses()
}

protocol CourseListDataStore {
    var courses: [Course] { get }
}

final class CourseListInteractor: CourseListBusinessLogic, CourseListDataStore {
    
    var presenter: CourseListPresentationLogic?
    var courses: [Course] = []
    
    // MARK: Do something
    
    func fetchCourses() {
        NetworkManager.shared.fetchData { [weak self] courses in
            self?.courses = courses
            
            let response = CourseList.ShowCourses.Response(courses: courses)
            self?.presenter?.presentCourses(response: response)
        }
    }
}
