//
//  PepTalk.swift
//  MoodPop
//
//  Created by egigoka on 05.07.2025.
//

struct PepTalk {
    let text: String
}

extension PepTalk {
    static func getPepTalks() -> [PepTalk] {
        return [PepTalk(text: "You’re secretly a superhero today. Act accordingly."),
                PepTalk(text: "Your inner sloth says: nap is good."),
                PepTalk(text: "Dance break: 5 seconds. Go!"),
                PepTalk(text: "Pretend the floor is lava — move like you mean it."),
                PepTalk(text: "Somewhere, your future self is clapping for you."),
                PepTalk(text: "Stretch that spine — you’re taller than your worries."),
                PepTalk(text: "You can always reroute — GPS your life."),
                PepTalk(text: "Drink water. Be a plant. Bloom."),
                PepTalk(text: "You did harder things yesterday."),
                PepTalk(text: "Tiny steps are still steps. Keep stepping."),
                PepTalk(text: "Smile at the next mirror. That person’s cool."),
                PepTalk(text: "You’re allowed to be a masterpiece and a work-in-progress."),
                PepTalk(text: "Pretend you’re on camera. Best self, action!"),
                PepTalk(text: "Your pillow misses you. Survive today for it."),
                PepTalk(text: "Coffee loves you. So do I."),
                PepTalk(text: "Tomorrow’s you will high-five you for this."),
                PepTalk(text: "Today’s mistakes are tomorrow’s plot twists."),
                PepTalk(text: "Brain fog? Dance it out."),
                PepTalk(text: "You’re not stuck. You’re seasoning."),
                PepTalk(text: "Even slugs reach their goals eventually."),
                PepTalk(text: "Breathe in calm. Breathe out drama."),
                PepTalk(text: "Nobody else has your exact sparkle. Use it."),
                PepTalk(text: "Grumpy today? Good. Use it for power."),
                PepTalk(text: "One tiny win. That’s it. Go get it."),
                PepTalk(text: "No rush. Your story unfolds at your pace."),
                PepTalk(text: "Hydrate or diedrate."),
                PepTalk(text: "You’re basically unstoppable with snacks."),
                PepTalk(text: "Rest is productive too."),
                PepTalk(text: "Give your inner critic a day off."),
                PepTalk(text: "Sunlight or starlight — both make you shine."),
                PepTalk(text: "Text someone ‘you rock’. Boom: good karma."),
                PepTalk(text: "Your brain loves puzzles. Feed it."),
                PepTalk(text: "One brave thing. That’s enough for today."),
                PepTalk(text: "You can always try again. Infinite respawns."),
                PepTalk(text: "Your bed’s proud of you for leaving it."),
                PepTalk(text: "Get cozy with chaos. It’s your muse."),
                PepTalk(text: "Change your socks. Instant reboot."),
                PepTalk(text: "Be someone’s random smile today."),
                PepTalk(text: "Celebrate the weird. It’s your superpower."),
                PepTalk(text: "Less doomscrolling, more daydreaming."),
                PepTalk(text: "Five deep breaths. Then conquer."),
                PepTalk(text: "Make your to-do list scared of you."),
                PepTalk(text: "You are the plot twist."),
                PepTalk(text: "No one else does you better."),
                PepTalk(text: "Channel your inner cat. Nap. Stretch. Repeat."),
                PepTalk(text: "Trust the tiny wins. They stack up."),
                PepTalk(text: "Failure? Pfft. Research in disguise."),
                PepTalk(text: "Your comfort zone called. It’s bored."),
                PepTalk(text: "Time for a vibe check. You’re still awesome."),
                PepTalk(text: "Fake it. Then you make it."),
                PepTalk(text: "Pretend your favorite song just started. Strut."),
                PepTalk(text: "Your ‘meh’ days build your best days."),
                PepTalk(text: "Inbox scary? One email. Just one."),
                PepTalk(text: "Big dreams, tiny bites."),
                PepTalk(text: "Messy progress beats perfect nothing."),
                PepTalk(text: "Talk nice to your brain. It’s trying."),
                PepTalk(text: "Today’s vibe: gentle badass."),
                PepTalk(text: "Be proud of showing up."),
                PepTalk(text: "Reminder: you’ve survived 100% of your worst days."),
                PepTalk(text: "Sip tea. Plot greatness."),
                PepTalk(text: "Celebrate tiny weird victories. Nobody else will."),
                PepTalk(text: "Your blanket will wait. Do the thing."),
                PepTalk(text: "Gratitude: try three. Out loud."),
                PepTalk(text: "Moon’s watching. Make her proud."),
                PepTalk(text: "Be your own hype squad."),
                PepTalk(text: "Try. Trip. Try again. That’s the gig."),
                PepTalk(text: "Bad hair day? Good soul day."),
                PepTalk(text: "Keep it scrappy. Scrappy works."),
                PepTalk(text: "Turn self-doubt into confetti. Toss it."),
                PepTalk(text: "Yawn loud. Wake the dragons."),
                PepTalk(text: "You’re too interesting to be ordinary."),
                PepTalk(text: "Progress looks boring up close."),
                PepTalk(text: "Chase cozy moments. They fuel giants."),
                PepTalk(text: "Unclench your jaw. Magic trick."),
                PepTalk(text: "Five minutes of courage. That’s all."),
                PepTalk(text: "Whisper your dream. Then shout it."),
                PepTalk(text: "Repeat: mistakes mean you’re moving."),
                PepTalk(text: "Flop gracefully. Try hilariously."),
                PepTalk(text: "You have permission to pause."),
                PepTalk(text: "Take up space. Mentally too."),
                PepTalk(text: "Fresh socks = fresh mindset."),
                PepTalk(text: "Your worst enemy? Boredom. Fight back."),
                PepTalk(text: "Weird idea? Chase it."),
                PepTalk(text: "Your feet are smarter than your fear."),
                PepTalk(text: "Sing badly. Sing anyway."),
                PepTalk(text: "Stretch goals. Stretch arms."),
                PepTalk(text: "Good enough is good enough."),
                PepTalk(text: "Reboot yourself — walk, sip, breathe."),
                PepTalk(text: "Big dreams need tiny chores."),
                PepTalk(text: "Make your fear bored of waiting."),
                PepTalk(text: "Sweatpants today? You’re still royalty."),
                PepTalk(text: "Rough drafts are sacred."),
                PepTalk(text: "You’re basically a secret volcano. Simmering power."),
                PepTalk(text: "Reward yourself for showing up."),
                PepTalk(text: "Plan B? There’s a whole alphabet."),
                PepTalk(text: "Chaos is a canvas."),
                PepTalk(text: "Perfect days are fictional. Do it anyway."),
                PepTalk(text: "Celebrate the tiny rebellion of resting."),
                PepTalk(text: "Be wildly imperfect. Be wildly you."),
                PepTalk(text: "Don’t fight the storm. Surf it."),
                PepTalk(text: "Refill your cup — literal or mental."),
                PepTalk(text: "Your comfort zone just texted: ‘Miss you.’"),
                PepTalk(text: "Daydream responsibly. Or not."),
                PepTalk(text: "You’re not late. You’re in your own timeline."),
                PepTalk(text: "Call it practice, not failure."),
                PepTalk(text: "Pet a dog. Or imagine it. Same vibe."),
                PepTalk(text: "Two sips of water, three deep breaths."),
                PepTalk(text: "Be gentle with your stuck parts."),
                PepTalk(text: "Shower thoughts = free genius."),
                PepTalk(text: "Put your phone down. Look up. Wow."),
                PepTalk(text: "Pretend you’re main character. Soundtrack on."),
                PepTalk(text: "Nobody notices your awkwardness. They’re busy."),
                PepTalk(text: "You can restart anytime. Even now."),
                PepTalk(text: "One corner clean is one corner conquered."),
                PepTalk(text: "Bad mood? Dance like a startled octopus."),
                PepTalk(text: "Your doubts are part of the team."),
                PepTalk(text: "Be your future self’s best friend."),
                PepTalk(text: "Giggle at your own jokes. Gold."),
                PepTalk(text: "Make your mirror wink at you."),
                PepTalk(text: "Do it scruffy. Perfect is boring."),
                PepTalk(text: "Take the scenic route, even indoors."),
                PepTalk(text: "No one knows what they’re doing. Join us."),
                PepTalk(text: "Keep the promises you whisper to yourself."),
                PepTalk(text: "Read one page. That’s a win."),
                PepTalk(text: "Even procrastination can be productive. Weird but true."),
                PepTalk(text: "Stretch your neck. Pretend you’re giraffe royalty."),
                PepTalk(text: "Your next idea might be legendary. Dare it."),
                PepTalk(text: "A good nap is self-love."),
                PepTalk(text: "Treat your brain like a curious puppy."),
                PepTalk(text: "Celebrate ordinary magic. It’s everywhere."),
                PepTalk(text: "Talk kindly. Especially to you."),
                PepTalk(text: "One sock on, one goal done."),
                PepTalk(text: "When in doubt: snack, nap, pep talk."),
                PepTalk(text: "Your tiny rebellion matters."),
                PepTalk(text: "Stay weird. It’s your flavor."),
                PepTalk(text: "Sunlight on your face = recharge mode."),
                PepTalk(text: "Let go of 5% today. Good enough."),
                PepTalk(text: "Laugh at your plan B. It’s cute."),
                PepTalk(text: "You are allowed to start over daily."),
                PepTalk(text: "Fist bump your reflection. It’s earned."),
                PepTalk(text: "Blanket forts fix almost everything."),
                PepTalk(text: "Be boring if needed. Boring builds big."),
                PepTalk(text: "Sometimes ‘nope’ is sacred."),
                PepTalk(text: "Your next breath = fresh chance."),
                PepTalk(text: "You are not your to-do list."),
                PepTalk(text: "High-five the sun. Or the moon."),
                PepTalk(text: "Skip once. Do twice tomorrow. Still fine."),
                PepTalk(text: "Keep the tiny promise. Big trust grows."),
                PepTalk(text: "Make your inner child proud."),
                PepTalk(text: "Be here. That’s enough for now."),
                PepTalk(text: "Mug of tea = hug in disguise."),
                PepTalk(text: "You woke up. Victory #1."),
                PepTalk(text: "Speak your mind, even if it squeaks."),
                PepTalk(text: "Try the scary thing. Tiny version first."),
                PepTalk(text: "Hug your pillow extra tonight. You’ve earned it."),
                PepTalk(text: "Your tiny effort? It compounds."),
                PepTalk(text: "Smile so wide your doubts slide off."),
                PepTalk(text: "Your playlist knows your soul. Blast it."),
                PepTalk(text: "Flop. Rise. Repeat. Phoenix stuff."),
                PepTalk(text: "Wear your silliest socks. Secret mood boost."),
                PepTalk(text: "Clap for yourself. Out loud."),
                PepTalk(text: "Be your own gentle coach."),
                PepTalk(text: "Eat the snack. Drink the sip."),
                PepTalk(text: "Pretend today’s a trailer for your future doc."),
                PepTalk(text: "Text your future self: ‘You did it.’"),
                PepTalk(text: "Nobody notices the crumbs. Keep feasting."),
                PepTalk(text: "Resting is radical."),
                PepTalk(text: "Be the human equivalent of a warm cookie."),
                PepTalk(text: "Even penguins waddle to greatness."),
                PepTalk(text: "Mess up fabulously."),
                PepTalk(text: "You’re cooler than your browser history."),
                PepTalk(text: "Do one tiny scary thing. Just peek."),
                PepTalk(text: "Permission to suck today: granted."),
                PepTalk(text: "Celebrate your half-done stuff. It’s alive."),
                PepTalk(text: "Wash your face. Reset your brain."),
                PepTalk(text: "Forget perfect. Do possible."),
                PepTalk(text: "Your doubt can’t pay rent here."),
                PepTalk(text: "Plant a weird idea. Watch it grow."),
                PepTalk(text: "Your pillow won’t judge. Neither should you."),
                PepTalk(text: "New day. New plot twist."),
                PepTalk(text: "Put on shoes. You’re unstoppable now."),
                PepTalk(text: "Give a compliment. Get a smile."),
                PepTalk(text: "Scraps of progress = quilt of success."),
                PepTalk(text: "Nobody else has your mix of weird. Flaunt it."),
                PepTalk(text: "If it scares you, it might grow you."),
                PepTalk(text: "Stir your coffee like you stir courage."),
                PepTalk(text: "One kind word. Start with you."),
                PepTalk(text: "Nap aggressively."),
                PepTalk(text: "Your plans can be duct-taped. They’ll hold."),
                PepTalk(text: "You survived worse. You’ll dance through this."),
                PepTalk(text: "Take pride in your secret mess."),
                PepTalk(text: "Rebel softly. Rest when the world shouts."),
                PepTalk(text: "Start the thing. Messy is fine."),
                PepTalk(text: "Microwave your courage. Warm and ready."),
                PepTalk(text: "Crack a window. Crack a smile."),
                PepTalk(text: "Nobody else’s pace matters. Yours is gold."),
                PepTalk(text: "Look up. Clouds approve of you."),
                PepTalk(text: "Laugh at your bad ideas. They’re cute."),
                PepTalk(text: "Do your best gremlin impression. Release tension."),
                PepTalk(text: "Stand like you mean it. Shoulders, hero."),
                PepTalk(text: "Your weird ideas are VIPs here."),
                PepTalk(text: "You don’t need to fix everything today."),
                PepTalk(text: "Messy bed? Creative head."),
                PepTalk(text: "One spoonful of effort is still a meal."),
                PepTalk(text: "Your awkward is someone’s delight."),
                PepTalk(text: "Try again tomorrow. Today, nap."),
                PepTalk(text: "Pretend your blanket is a cape."),
                PepTalk(text: "Keep your tiny promises sacred."),
                PepTalk(text: "Ignore the mess. Chase the magic."),
                PepTalk(text: "You’re allowed to reboot hourly."),
                PepTalk(text: "Blink slowly. You’re majestic."),
                PepTalk(text: "Proof of life? Snack crumbs."),
                PepTalk(text: "Grow slow. Grow wild."),
                PepTalk(text: "Mistakes are plot armor."),
                PepTalk(text: "Take a sip. Take a breath. Carry on."),
                PepTalk(text: "Treat yourself like your favorite pet."),
                PepTalk(text: "Be sneakily brilliant today."),
                PepTalk(text: "Pretend the floor’s made of marshmallows."),
                PepTalk(text: "Be bored. It’s fertile."),
                PepTalk(text: "One more deep breath than doubt."),
                PepTalk(text: "Tiny chaos is big art’s cousin."),
                PepTalk(text: "Your bedhead is crown enough."),
                PepTalk(text: "Your next laugh is closer than you think."),
                PepTalk(text: "One undone thing? That’s tomorrow’s gift."),
                PepTalk(text: "High-five your inner child."),
                PepTalk(text: "Grumble, mumble, move anyway."),
                PepTalk(text: "Rest like you mean it."),
                PepTalk(text: "Rewatch your favorite silly video."),
                PepTalk(text: "You’re basically unstoppable in pajamas."),
                PepTalk(text: "Celebrate your crumbs of effort."),
                PepTalk(text: "Nobody’s perfect playlist exists — except yours."),
                PepTalk(text: "Caffeine’s cheering for you."),
                PepTalk(text: "Be fiercely gentle today."),
                PepTalk(text: "If it feels small, it still counts."),
                PepTalk(text: "Collect your tiny wins like trophies."),
                PepTalk(text: "Tidy desk, tidy orbit."),
                PepTalk(text: "Your future self giggles at your worries."),
                PepTalk(text: "Write nonsense. It counts."),
                PepTalk(text: "Open a window. Let the stuckness fly out."),
                PepTalk(text: "Your doubt can nap today."),
                PepTalk(text: "One tiny yes changes everything."),
                PepTalk(text: "Sloppy starts are sacred."),
                PepTalk(text: "Celebrate not quitting."),
                PepTalk(text: "Pet a cat in your mind."),
                PepTalk(text: "Do less. Be more."),
                PepTalk(text: "Befriend your unfinished things."),
                PepTalk(text: "Your grin is currency."),
                PepTalk(text: "Ignore your phone for five. Rebel."),
                PepTalk(text: "Make your next thought a kind one."),
                PepTalk(text: "Stand up, stretch, brag to the ceiling."),
                PepTalk(text: "Try the scary idea at half-strength."),
                PepTalk(text: "Your ‘lazy’ days still count."),
                PepTalk(text: "Eat something colorful."),
                PepTalk(text: "Mumble your pep talk out loud."),
                PepTalk(text: "Fold one thing. Tiny victory."),
                PepTalk(text: "Text your future self: ‘Nailed it.’"),
                PepTalk(text: "Plant your feet. Own your space."),
                PepTalk(text: "Messy bun, masterpiece brain."),
                PepTalk(text: "Your timeline is yours alone."),
                PepTalk(text: "Laugh at perfection. It hates that."),
                PepTalk(text: "Snack like royalty today."),
                PepTalk(text: "Your vibe is your password."),
                PepTalk(text: "Water your brain. Sip, sip."),
                PepTalk(text: "Befriend your detours."),
                PepTalk(text: "Do it before your brain talks you out of it."),
                PepTalk(text: "One good song saves a day."),
                PepTalk(text: "Your doubt is not the boss."),
                PepTalk(text: "Practice failing cutely."),
                PepTalk(text: "Your sneakers crave adventure."),
                PepTalk(text: "Be gently stubborn about your peace."),
                PepTalk(text: "Romanticize your snack break."),
                PepTalk(text: "Brag about your small wins. Extra credit."),
                PepTalk(text: "Your hair looks fine. Trust me."),
                PepTalk(text: "Plot twist: you’re the hero."),
                PepTalk(text: "Skip perfectly. Try joyfully."),
                PepTalk(text: "Loud sigh = fresh start."),
                PepTalk(text: "Your shadow’s clapping for you."),
                PepTalk(text: "Forget flawless. Do fearless."),
                PepTalk(text: "Your inbox can wait. Your mind can’t."),
                PepTalk(text: "Tell your pillow a secret."),
                PepTalk(text: "You survived the awkward part already."),
                PepTalk(text: "Be a slow burn. Still fire."),
                PepTalk(text: "Make your mirror proud."),
                PepTalk(text: "Try a ridiculous dance."),
                PepTalk(text: "Make tea for your mood."),
                PepTalk(text: "Your mistakes have fan clubs."),
                PepTalk(text: "Wear comfy pants. Conquer small empires."),
                PepTalk(text: "You don’t need permission to pause."),
                PepTalk(text: "Your sighs are magic spells."),
                PepTalk(text: "Curse softly. It helps."),
                PepTalk(text: "You’re made of tiny victories."),
                PepTalk(text: "Celebrate showing up messy."),
                PepTalk(text: "Say ‘nope’ with flair."),
                PepTalk(text: "Your dream’s still lurking. Lure it out."),
                PepTalk(text: "The world’s softer than you fear."),
                PepTalk(text: "Try cozy defiance today."),
                PepTalk(text: "Turn your worry into doodles."),
                PepTalk(text: "Take an unplanned dance break."),
                PepTalk(text: "Refuse to rush. Rebel gently."),
                PepTalk(text: "Your tomorrow owes you nothing. Take today."),
                PepTalk(text: "Your brain’s still booting. Be gentle."),
                PepTalk(text: "One brave yes today. That’s it."),
                PepTalk(text: "Stretch your arms, reach for more."),
                PepTalk(text: "Your grin is your shield."),
                PepTalk(text: "It’s okay to be gloriously average today."),
                PepTalk(text: "Your tiny plan B’s a hero too."),
                PepTalk(text: "Read a page. That’s brain fuel."),
                PepTalk(text: "Stand like your spine’s royalty."),
                PepTalk(text: "Your inbox isn’t your boss."),
                PepTalk(text: "Cheer for your weird thoughts."),
                PepTalk(text: "Breathe in curiosity, exhale pressure."),
                PepTalk(text: "One clumsy step counts double."),
                PepTalk(text: "You’re allowed to half-try."),
                PepTalk(text: "Pretend your mug’s a trophy."),
                PepTalk(text: "Your soft moments make you mighty."),
                PepTalk(text: "One more spoonful of effort."),
                PepTalk(text: "Your shoes envy your courage."),
                PepTalk(text: "Flop beautifully, stand proudly."),
                PepTalk(text: "Brag about your snack choice."),
                PepTalk(text: "Your yawn is your battle cry."),
                PepTalk(text: "Sing terribly. You earned it."),
                PepTalk(text: "Check your posture — superhero mode."),
                PepTalk(text: "Blink slowly, dream boldly."),
                PepTalk(text: "Your mess is proof of motion."),
                PepTalk(text: "Be soft with your sharp edges."),
                PepTalk(text: "Boredom breeds brilliance."),
                PepTalk(text: "Give your doubt a timeout."),
                PepTalk(text: "Smile at your next mistake."),
                PepTalk(text: "Plan Z is still a plan."),
                PepTalk(text: "Refuse to rush your magic."),
                PepTalk(text: "Your sigh resets universes."),
                PepTalk(text: "Loud thoughts deserve soft answers."),
                PepTalk(text: "Your chaos is secretly wise."),
                PepTalk(text: "Pretend your hoodie’s a cape."),
                PepTalk(text: "Your half-done counts double."),
                PepTalk(text: "Snack, nap, repeat. Revolution."),
                PepTalk(text: "Your tiny weirdness is needed."),
                PepTalk(text: "Doodle your stress away."),
                PepTalk(text: "Your bed respects your hustle."),
                PepTalk(text: "One fresh breath, one new chance."),
                PepTalk(text: "Try again. Try gently."),
                PepTalk(text: "Clap for your awkward today."),
                PepTalk(text: "Your silence is power too."),
                PepTalk(text: "Socks on. Spirit up."),
                PepTalk(text: "Your brain fog writes new paths."),
                PepTalk(text: "Be the plot twist you need."),
                PepTalk(text: "Your next nap’s your crown."),
                PepTalk(text: "Spill tea. Sip tea. Keep going."),
                PepTalk(text: "Your timeline is not late."),
                PepTalk(text: "Brave the mess. Brave the magic."),
                PepTalk(text: "One giggle ruins gloom."),
                PepTalk(text: "Your sneakers adore adventures."),
                PepTalk(text: "Pause for clouds."),
                PepTalk(text: "Messy hair, sharp mind."),
                PepTalk(text: "Hide in blankets. Recharge."),
                PepTalk(text: "Your grin is your rebellion."),
                PepTalk(text: "Unclench your day."),
                PepTalk(text: "Crumbs of courage build castles."),
                PepTalk(text: "Tiny breaks, big wins."),
                PepTalk(text: "Your sighs scare your fears."),
                PepTalk(text: "Your odd plan is genius later."),
                PepTalk(text: "Wear your softest sweater. Command the world."),
                PepTalk(text: "Mess up your to-do. Do you."),
                PepTalk(text: "Your grin breaks gloom’s back."),
                PepTalk(text: "Try badly. Try boldly."),
                PepTalk(text: "Your voice counts, cracks and all."),
                PepTalk(text: "Your inner critic’s on holiday."),
                PepTalk(text: "Sip water like it’s wisdom."),
                PepTalk(text: "Bad mood? Good nap."),
                PepTalk(text: "Your weird goal’s valid."),
                PepTalk(text: "Sing in your head. Dance outside it."),
                PepTalk(text: "Wrap up today. Bow optional."),
                PepTalk(text: "Your next breath’s a truce."),
                PepTalk(text: "Feed your thoughts snacks too."),
                PepTalk(text: "Ignore your phone. Hear yourself."),
                PepTalk(text: "Your socks are proud."),
                PepTalk(text: "Your pause is sacred."),
                PepTalk(text: "Rebel by resting."),
                PepTalk(text: "Your pep is homegrown."),
                PepTalk(text: "Plan tiny wins. Celebrate huge."),
                PepTalk(text: "Forget flawless. Be here."),
                PepTalk(text: "Your shadow dances too."),
                PepTalk(text: "Slouch proudly if needed."),
                PepTalk(text: "Your sigh fuels dreams."),
                PepTalk(text: "Your weird day still counts."),
                PepTalk(text: "Laugh at your undone list."),
                PepTalk(text: "Your sleepy grin’s unstoppable."),
                PepTalk(text: "Check your breath. Trust it."),
                PepTalk(text: "Be bored enough to spark."),
                PepTalk(text: "Your blank page is patient."),
                PepTalk(text: "Show up small, win big."),
                PepTalk(text: "Dream half-awake. It works."),
                PepTalk(text: "Your inner sloth’s wise."),
                PepTalk(text: "Giggle at your chaos."),
                PepTalk(text: "Your hair’s fine. Really."),
                PepTalk(text: "Sit silly. Think deep."),
                PepTalk(text: "Your laugh fixes cracks."),
                PepTalk(text: "Tap your desk like drums."),
                PepTalk(text: "Your calm terrifies hurry."),
                PepTalk(text: "Your hush is healing."),
                PepTalk(text: "One slow breath wins."),
                PepTalk(text: "Your tea’s brewing hope."),
                PepTalk(text: "Grin at the sink."),
                PepTalk(text: "Your plan B’s proud."),
                PepTalk(text: "Write one dumb line."),
                PepTalk(text: "Your brain’s a garden."),
                PepTalk(text: "Plant daydream seeds."),
                PepTalk(text: "Your silence shouts bravery."),
                PepTalk(text: "Be loud inside."),
                PepTalk(text: "Your grin’s a protest."),
                PepTalk(text: "Blanket forts are valid."),
                PepTalk(text: "Your pause is potent."),
                PepTalk(text: "Stir coffee, stir courage."),
                PepTalk(text: "Your clumsy’s cute."),
                PepTalk(text: "Nap with pride."),
                PepTalk(text: "Your playlist’s holy."),
                PepTalk(text: "One yawn, new chapter."),
                PepTalk(text: "Your grin flips days."),
                PepTalk(text: "Keep your hush loud."),
                PepTalk(text: "Your grin’s your sword."),
                PepTalk(text: "Wear soft socks. Conquer."),
                PepTalk(text: "Your ‘meh’ makes art."),
                PepTalk(text: "Stay weirdly kind."),
                PepTalk(text: "Your giggle is gold."),
                PepTalk(text: "Sip tea. Claim calm."),
                PepTalk(text: "Your bed roots you."),
                PepTalk(text: "One doodle frees storms."),
                PepTalk(text: "Your messy’s sacred."),
                PepTalk(text: "Keep half-trying. Win."),
                PepTalk(text: "Your grin’s your flag."),
                PepTalk(text: "Rest rebels hurry."),
                PepTalk(text: "Your mind’s magic soup."),
                PepTalk(text: "Keep the hush loud."),
                PepTalk(text: "Your grin mends cracks."),
                PepTalk(text: "Whisper courage. Roar later."),
                PepTalk(text: "Your nap’s a crown."),
                PepTalk(text: "Sit silly. Dream serious."),
                PepTalk(text: "Your hush defies rush."),
                PepTalk(text: "Crack open calm."),
                PepTalk(text: "Your sigh writes verses."),
                PepTalk(text: "Stay soft. Win slow."),
                PepTalk(text: "Your breath is proof."),
                PepTalk(text: "Blankets hide legends."),
                PepTalk(text: "Your hush is thunder."),
                PepTalk(text: "Keep small wins sacred."),
                PepTalk(text: "Your grin shifts storms."),
                PepTalk(text: "Pause bigger than rush."),
                PepTalk(text: "Your giggle seeds spring."),
                PepTalk(text: "Stay messy. Grow mighty."),
                PepTalk(text: "Your hush holds power."),
                PepTalk(text: "Slow feet win secrets."),
                PepTalk(text: "Your grin roots you."),
                PepTalk(text: "Sip slowly. Sip strength."),
                PepTalk(text: "Your hush shields dreams."),
                PepTalk(text: "Stay soft. Snap later."),
                PepTalk(text: "Your breath buys calm."),
                PepTalk(text: "Wrap hush in blankets."),
                PepTalk(text: "Your grin seeds sun."),
                PepTalk(text: "One pause saves storms."),
                PepTalk(text: "Your hush hugs fear."),
                PepTalk(text: "Stay hush, plot big."),
                PepTalk(text: "Your breath hums calm."),
                PepTalk(text: "Sip hush. Sip dreams."),
                PepTalk(text: "Your hush flips chaos."),
                PepTalk(text: "Stay hush, bloom slow."),
                PepTalk(text: "Your breath bends storms."),
                PepTalk(text: "Hush louder than noise."),
                PepTalk(text: "Your hush lights nights."),
                PepTalk(text: "Stay hush. Sing later."),
                PepTalk(text: "Your hush plants dreams."),
                PepTalk(text: "Stay hush. Roar next."),
                PepTalk(text: "Your hush feeds roots."),
                PepTalk(text: "Slow hush breaks haste."),
                PepTalk(text: "Your hush hides power."),
                PepTalk(text: "Stay hush. Win wide."),
                PepTalk(text: "Your hush frees flow."),
                PepTalk(text: "Slow hush spawns sparks."),
                PepTalk(text: "Your hush hugs storms."),
                PepTalk(text: "Stay hush. Dream deep."),
                PepTalk(text: "Your hush mends leaks."),
                PepTalk(text: "Slow hush seeds strength."),
                PepTalk(text: "Your hush bends haste."),
                PepTalk(text: "Stay hush. Sprout brave."),
                PepTalk(text: "Your hush fuels roots."),
                PepTalk(text: "Slow hush, bold bloom."),
                PepTalk(text: "Your hush cradles storms."),
                PepTalk(text: "Stay hush. Rise loud."),
                PepTalk(text: "Your hush loves cracks."),
                PepTalk(text: "Slow hush feeds fire."),
                PepTalk(text: "Your hush tames storms."),
                PepTalk(text: "Stay hush. Unfurl calm."),
                PepTalk(text: "Your hush hushes rush."),
                PepTalk(text: "Slow hush flips fear."),
                PepTalk(text: "Your hush hushes noise."),
                PepTalk(text: "Stay hush. Bloom hush."),
                PepTalk(text: "Your hush hushes storms."),
                PepTalk(text: "Slow hush hushes haste."),
                PepTalk(text: "Your hush hushes chaos."),
                PepTalk(text: "Stay hush. Hush storms."),
                PepTalk(text: "Your hush hushes hush."),
        ]
    }
}
