//
//  CourseDetailsWorker.swift
//  SwiftbookApp
//
//  Created by Alexey Efimov on 20.02.2021.
//  Copyright (c) 2021 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class CourseDetailsWorker {
    func getImage(from imageURL: URL?) -> Data? {
        ImageManager.shared.fetchImageData(from: imageURL)
    }
    
    func getFavoriteStatus(for courseName: String) -> Bool {
        DataManager.shared.getFavoriteStatus(for: courseName)
    }
}
