//
//  CourseDetailsPresenter.swift
//  SwiftbookApp
//
//  Created by Alexey Efimov on 20.02.2021.
//  Copyright (c) 2021 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CourseDetailsPresentationLogic {
    func presentCourseDetails(response: CourseDetails.ShowDetails.Response)
}

final class CourseDetailsPresenter: CourseDetailsPresentationLogic {
    
    weak var viewController: CourseDetailsDisplayLogic?
    
    func presentCourseDetails(response: CourseDetails.ShowDetails.Response) {
        let numberOfLessons = "Number of lessons: \(response.numberOfLessons ?? 0)"
        let numberOfTests = "Number of tests: \(response.numberOfTests ?? 0)"
        
        let viewModel = CourseDetails.ShowDetails.ViewModel(
            courseName: response.courseName ?? "NONAME",
            numberOfLessons: numberOfLessons,
            numberOfTests: numberOfTests,
            imageData: response.imageData ?? Data()
        )
        viewController?.displayCourseDetails(viewModel: viewModel)
    }
}
