//
//  CourseDetailsWorker.swift
//  SwiftbookApp
//
//  Created by Alexey Efimov on 20.02.2021.
//  Copyright (c) 2021 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class CourseDetailsWorker {

    func getImage(from imageURL: URL?) -> Data? {
        if let cached = ImageManager.shared.cachedImageData(for: imageURL) {
            return cached
        }
        // Cache miss: warm cache off main thread. Sync chain keeps
        // original shape, so this pass returns nil, cached next time.
        Task {
            _ = await ImageManager.shared.fetchImageData(from: imageURL)
        }
        return nil
    }
    
    func getFavoriteStatus(for courseName: String) -> Bool {
        DataManager.shared.getFavoriteStatus(for: courseName)
    }
    
    func setNewFavoriteStatus(for courseName: String, with status: Bool) {
        DataManager.shared.setFavoriteStatus(for: courseName, with: status)
    }
}
