//
//  CourseDetailsPresenter.swift
//  SwiftbookApp
//
//  Created by Alexey Efimov on 20.02.2021.
//  Copyright (c) 2021 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CourseDetailsPresentationLogic {
    func presentSomething(response: CourseDetails.Something.Response)
}

final class CourseDetailsPresenter: CourseDetailsPresentationLogic {
    
    weak var viewController: CourseDetailsDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: CourseDetails.Something.Response) {
        let viewModel = CourseDetails.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
