//
//  CourseDetailsInteractor.swift
//  SwiftbookApp
//
//  Created by Alexey Efimov on 20.02.2021.
//  Copyright (c) 2021 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CourseDetailsBusinessLogic {
    var isFavorite: Bool { get }
    func provideCourseDetails(request: CourseDetails.ShowDetails.Request)
}

protocol CourseDetailsDataStore {
    var course: Course? { get }
}

final class CourseDetailsInteractor: CourseDetailsBusinessLogic, CourseDetailsDataStore {
    
    var presenter: CourseDetailsPresentationLogic?
    var worker: CourseDetailsWorker?
    var course: Course?
    var isFavorite = false
    
    // MARK: Do something
    
    func provideCourseDetails(request: CourseDetails.ShowDetails.Request) {
        course = request.course
        worker = CourseDetailsWorker()
        isFavorite = worker?.getFavoriteStatus(for: course?.name ?? "") ?? false
        let imageData = worker?.getImage(from: course?.imageUrl)
        
        let response = CourseDetails.ShowDetails.Response(
            courseName: course?.name,
            numberOfLessons: course?.numberOfLessons,
            numberOfTests: course?.numberOfTests,
            imageData: imageData,
            isFavorite: isFavorite
        )
        presenter?.presentCourseDetails(response: response)
    }
}
