//
//  CourseDetailsModels.swift
//  SwiftbookApp
//
//  Created by Alexey Efimov on 20.02.2021.
//  Copyright (c) 2021 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CourseDetails {
    // MARK: Use cases
    enum ShowDetails {
        
        struct Request: Sendable {
            let course: Course
        }
        
        struct Response: Sendable {
            let courseName: String?
            let numberOfLessons: Int?
            let numberOfTests: Int?
            let imageData: Data?
        }
        
        struct ViewModel: Sendable {
            let courseName: String
            let numberOfLessons: String
            let numberOfTests: String
            let imageData: Data
        }
    }
}
