//
//  CourseDetailsInteractor.swift
//  SwiftbookApp
//
//  Created by Alexey Efimov on 20.02.2021.
//  Copyright (c) 2021 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CourseDetailsBusinessLogic {
    func doSomething(request: CourseDetails.Something.Request)
}

protocol CourseDetailsDataStore {
    //var name: String { get set }
}

final class CourseDetailsInteractor: CourseDetailsBusinessLogic, CourseDetailsDataStore {
    
    var presenter: CourseDetailsPresentationLogic?
    var worker: CourseDetailsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: CourseDetails.Something.Request) {
        worker = CourseDetailsWorker()
        worker?.doSomeWork()
        
        let response = CourseDetails.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
