# Uncomment the next line to define a global platform for your project
platform :ios, '26.0'

target 'FlightTimeline' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TimelineTableViewCell', :path => './TimelineTableViewCell'

  # Pods for FlightTimeline

end
